### ISSUE TITLE
Some drawbacks on audio upsampling.

### ISSUE THREAD

**Issue by deardeerluluu** [YangYang/adversarial_train_for_speech_super_resolution#1]
Hi~Nice to meet you!
I wonder if you have met such problems in reconstructing the frequency in audio clips from low-res to high-res:

there is an annoying line in the highest frequency 

(for example:
![download](https://user-images.githubusercontent.com/51529731/62679066-e0b33100-b9e5-11e9-8f3c-a37c2c43965d.png)

I want to achieve the goal of exchanging the audio from 8k to 16k (which means the original highest frequency may be 4k), and I found the output after training appears noise around 4k, no matter I try training on frequency domain or directly on time domain.

Have you ever met such case? Do you have any ideas to handle this problem? I'' be really appreciated if you reply me. 

thx!!!

**Comment by YangYang** [comment]
Although I'm not meet this case, I noticed the author of the paper provide a solution of the frequency discontinuity on the concatenation position is "predict the highest C frequency bins of the narrowband spectrogram".
I hope this helps.
If you are in china and want to comunicate with the experiment of  Super Speech-Resolution in deeply, and you may contact with me in wechat. Please note your github nickname.
My wechat(base64) : eXkxODY0NzcwNTA1Mgo=
