### ISSUE TITLE
Could not able to run the adversarial network training for Speech Super Resolution task

### ISSUE THREAD

**Issue by RambabuBanothu** [YangYang/adversarial_train_for_speech_super_resolution#2]
Hi, I am interested in adversarial network training for SSR-GAN.
Could not able to run the adversarial network training for Speech Super Resolution task. Could you give the directory structure and readme for execution of your codes.

**Comment by YangYang** [comment]
Sorry, this repository was created 3 years ago and I am not focusing on the SSR with GAN already.
But this work will be still open sources, hoping the code could help you.
Have a good luck.

**Comment by RambabuBanothu** [comment]
Thanks for your reply, i could not find any instructions or readme for this
work. The code comments are also in your own language. If any support from
you will greatly help. Thank you once again for your support.

**Comment by YangYang** [comment]
The entrance of this project is in /a_train, where each '.py' has a different setting (since I am very naive at 3 years ago.
And other codes of SSR-GAN will study by yourself.
